### ISSUE TITLE
Questions about num_rels

### ISSUE THREAD

**Issue by benjpau** [HKUST-KnowComp/BMGF-RoBERTa#2]
parser.add_argument("--num_rels", type=int, default=4,
                  choices=[3, 4, 11, 12, 14],
                  help="how many relations are computed")

The choices of the hyper-parameter _num_rels_ is [3, 4, 11, 12, 14], but in the conll dataset, the class is 15. So how to choose _num_rels_ for the conll dataset?
By the way, could you please offer the whole hyper-parameters for the conll dataset? And, could you please describe the meaning of [3, 4, 11, 12, 14], respectively?

**Comment by seanliu96** [comment]
Hi, thanks for your questions. In CoNLL share task, there are 14 discourse relations + *EntRel*. However, *EntRel* is not included in the implicit part. Hence, you can directly set the *num_rels* as 14 for the CoNLL data.

As for another settings, 4 corresponds to the *Comparison*, *Contingency*, *Expansion*, and *Temporal*, which are the four top topics; 11 corresponds to *Comparison.Concession*, *Comparison.Contrast*, *Contingency.Cause*, *Contingency.Pragmatic cause*. *Expansion.Alternative*, *Expansion.Conjunction*. *Expansion.Instantiation*. *Expansion.List*, *Expansion.Restatement*, *Temporal.Asynchronous*, and *Temporal.Synchrony*, which are the eleven second-level senses.

It seems 3 and 12 are not belonging to the implicit classification task, so you can ignore them.

**Comment by benjpau** [comment]
Thanks for your reply!
